### ISSUE TITLE
Disable pings/@everyone and/or allow us to use embeds

### ISSUE THREAD

**Issue by Aida-Enna** [reiichi001/Dalamud.DiscordBridge#10]
![image](https://user-images.githubusercontent.com/5483362/134755806-fdf2c8b3-75bf-4d21-8cd9-71c1a58b5d38.png)

**Comment by Aida-Enna** [comment]
For reasons I cannot understand, even giving the bot only a role with no admin permissions and @everyone turned off -still- lets it ping everyone.

**Comment by reiichi001** [comment]
The next release will be explicitly blocking `@everyone` and `@here` from DiscordBridge's chat relay for game messages per commit https://github.com/reiichi001/Dalamud.DiscordBridge/commit/8ce9feafa00e568837db2bb157d3f042c8f93326. Retainer sales will still allow it, should someone set a ping as a chat channel prefix.

Normal role/user pings as prefixes will also continue to work.
![image](https://user-images.githubusercontent.com/10376708/138617896-d0f0ea36-c1e2-44c3-9539-9777d6f1ea75.png)
