### ISSUE TITLE
Ability to remove cross-world party chat from channel set menu

### ISSUE THREAD

**Issue by Oukar** [reiichi001/Dalamud.DiscordBridge#13]
Currently, the identifier for party chat and cross-world party chat are both p, and setting 'any' puts all the chat types together, but unset p only removes regular party chat. There doesn't seem to be any way to remove cross-world party chat from the settings.
![image](https://user-images.githubusercontent.com/4054715/148568449-ee0ad10c-4e5d-4988-9ada-2072f9e540c5.png)

![image](https://user-images.githubusercontent.com/4054715/148568576-3f84f187-e583-4dc5-9baa-eee3ce98db1d.png)

**Comment by reiichi001** [comment]
This should be resolved now. Party and Crossworld Party are handled a bit strangely here, as they're different chat type numbers internal to the game, but not to the chat box. We've tried to replicate a consistent experience, but it took some massaging.
