### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kwehh13** [reiichi001/Dalamud.DiscordBridge#16]
Is there anyway to show "___ has joined your party" messages? I can't figure out which one logs those
On that topic, is there one for players logging in and out too?

Also what is IPC chat type?

(Feature Request)
Is it possible to make the bot ping a user if a specific word shows up in chat

Edit: 8761 is the chat id for joining and leaving parties if that helps

**Comment by reiichi001** [comment]
Party joins are part of System Messages (sysmsg) types. As of DiscordBridge 1.2.6.0, you'll get them from the sysmsg chat type as the plugin no longer treats different sender masks as different types.

The IPC chat type is a custom chat channel used for integrating with other plugins. That way, a plugin can send a message through DiscordBridge without having to print it to the chat box as a specific type.
