### ISSUE TITLE
xl!togglesender fails to print player names

### ISSUE THREAD

**Issue by pendragonair** [reiichi001/Dalamud.DiscordBridge#31]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

With xl!togglesender and xl!toggledefaultnameavatar both enabled, Dalamud.DiscordBridge bot only prints "FFXIV Bridge Worker Unknown LocalPlayer" as the character name regardless of who sent the message. Chat messages are parsed correctly according to channel. A restart doesn't seem to fix the problem. Test messages are from myself. With xl!toggledefaultnameavatar *disabled*, the issue remains.

![image](https://github.com/reiichi001/Dalamud.DiscordBridge/assets/85573800/00ec3faf-15c3-4e6c-9c69-8625d459104c)
![image](https://github.com/reiichi001/Dalamud.DiscordBridge/assets/85573800/87db713d-4394-4a33-9959-7e3035b3c435)

### Platform

Windows

**Comment by pendragonair** [comment]
After a couple instances of restarting, for some reason this issue is fixed. However, I'm not sure if it's intermittent?

**Comment by reiichi001** [comment]
DiscordBridge relies on Dalamud services to get the local player (your logged-in character). Previously, it fetched this on demand and outside of the game's Framework thread. In Dalamud API 9, doing so was deprecated and would spam the log with warnings.

I got some tips on how to switch this to a cache on login/logout, but it seems that wasn't quite enough. DiscordBridge 1.5.0.1 will now update the cache every framework tick, which should work more like previous versions, at the cost of being more fickle on framework updates if those hang.
