### ISSUE TITLE
make it work both ways?

### ISSUE THREAD

**Issue by owaimori** [reiichi001/Dalamud.DiscordBridge#4]
an option to send messages from discord channel to FFXIV too? that allow us to chat in discord trough the game

it can be done directly in FFXIV chat like plugin updates or in a separate plugin window, with working emoji and images

**Comment by squidmade** [comment]
@reiichi001 Is this something you'd be open to adding to the plugin if a PR was made?

**Comment by reiichi001** [comment]
> @reiichi001 Is this something you'd be open to adding to the plugin if a PR was made?

This is a tricky one IMO. I've considered the idea of being able to map a Discord channel for relay into the in-game chatbox (so no sending messages to the actual game server) similar to how we send in-game chat to Discord in a non-interactive way. 

On the other hand, sending messages to the actual game servers through XIVCommon or something is technically doable, but involves a bit of risk as you'd have to sanitize all input to check for invalid characters, message length, and strip out things that shouldn't be there like `:emoji:` or `<@usermentions>` (or at least resolve these to a plain text version). I'm not confident in doing this correctly, and it's something that would need to be tested heavily before public release.
