### ISSUE TITLE
Option to remove the "chat kinds" name when using a prefix

### ISSUE THREAD

**Issue by holodrum** [reiichi001/Dalamud.DiscordBridge#9]
For example, for party chat, I use the prefix ":partying_face:" and it would look so much better if only that showed up, instead of ":partying_face:  [party]"

Awesome work on everything else, this plugin/bot is simply put absolutely amazing :)

**Comment by rrbailey89** [comment]
I second this... except id like the option to remove the prefix all together

**Comment by rossmjr** [comment]
Thirded, I thought I could get around it with "" but the [] remains
